apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demand-forecast-prod

resources:
  - ../../base
  - ../../base/secrets
  - ../../../policies
  - secret-store.yaml

patches:
  - path: replicas.yaml
    target: { kind: Deployment, name: demand-forecast }

commonLabels:
  environment: prod
  cloud: aws
