apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demand-forecast-dev

resources:
  - ../../base
  - ../../../policies

patches:
  - path: replicas.yaml
    target: { kind: Deployment, name: demand-forecast }

commonLabels:
  environment: dev
  cloud: aws
