#!/usr/bin/env python3
"""Measure what each local-stack container actually uses, and record it against its image.

QA-4 round eighteen found Grafana 13.2.2 OOMKilled at its 200Mi limit on every
start. It had been bumped from 11 two weeks earlier (#72, "verified against the
suite", which never starts the stack), and nothing that ran on that change ever
started the image. A limit chosen for one image and inherited by the next is a
guess about software nobody ran.

So `platform/local/measured-memory.yaml` records, per component, the image
it was measured with and its peak working set on a running cluster, and
`tests/test_local_memory_budget.py` fails when a manifest's image differs from the
measured one, or its limit in `platform/local/budget.yaml` leaves less than
`HEADROOM` over the peak. A bump —
Dependabot's included — cannot merge until someone has run the stack with it:

    make local-up                                         # the stack, at the new image
    uv run python scripts/local/measure_memory.py         # report
    uv run python scripts/local/measure_memory.py --write # record it in measured-memory.yaml

Sampled from the kind node with `crictl stats` — the kubelet's own working-set
figure, the one the OOM killer acts on — several times, taking the peak. It
refuses to record a component whose container has restarted or been OOMKilled,
because the peak of a container that keeps dying is not its need.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
BUDGET = REPO_ROOT / "platform" / "local" / "budget.yaml"
LEDGER = REPO_ROOT / "platform" / "local" / "measured-memory.yaml"
_LEDGER_HEADER = (
    "# GENERATED by `uv run python scripts/local/measure_memory.py --write` on a running local stack.\n"
    "# Never edited by hand: each entry is what that image used, measured, and the limit in\n"
    "# platform/local/budget.yaml must exceed it by `headroom` (tests/test_local_memory_budget.py).\n"
)
CLUSTER = "ml-platform-local"
NODE = f"{CLUSTER}-control-plane"
NAMESPACE = "ml-platform"

#: The limit must exceed the measured peak by this factor: a working set grows
#: with dashboards provisioned, series scraped and objects stored.
HEADROOM = 1.25

#: Termination reasons that mean the process failed, not the node restarting.
_FAILURES = frozenset({"OOMKilled", "Error", "ContainerCannotRun", "CrashLoopBackOff"})

#: Container name in the pod → component name in budget.yaml, where they differ.
_COMPONENT = {"collector": "otel-collector"}


def _run(command: list[str]) -> str:
    done = subprocess.run(command, capture_output=True, text=True, timeout=120, check=False)
    if done.returncode != 0:
        raise RuntimeError(f"{' '.join(command)} failed: {done.stderr.strip()}")
    return done.stdout


def _pods() -> dict[str, dict[str, Any]]:
    """Each container in the namespace: its image as declared, restart count, last termination reason."""
    pods = json.loads(_run(["kubectl", "--context", f"kind-{CLUSTER}", "-n", NAMESPACE, "get", "pods", "-o", "json"]))
    found: dict[str, dict[str, Any]] = {}
    for pod in pods["items"]:
        declared = {c["name"]: c["image"] for c in pod["spec"]["containers"]}
        for status in pod.get("status", {}).get("containerStatuses", []):
            name = status["name"]
            last = (status.get("lastState") or {}).get("terminated") or {}
            found[_COMPONENT.get(name, name)] = {
                "image": declared[name],
                "restarts": status.get("restartCount", 0),
                "last_reason": last.get("reason"),
                "ready": status.get("ready", False),
            }
    return found


def _working_sets() -> dict[str, int]:
    """Working set in MiB per container in the namespace, from the node's own stats."""
    stats = json.loads(_run(["docker", "exec", NODE, "crictl", "stats", "-o", "json"]))
    found: dict[str, int] = {}
    for entry in stats.get("stats", []):
        labels = entry.get("attributes", {}).get("labels", {})
        memory = entry.get("memory") or {}
        if labels.get("io.kubernetes.pod.namespace") != NAMESPACE or "workingSetBytes" not in memory:
            continue
        name = labels["io.kubernetes.container.name"]
        found[_COMPONENT.get(name, name)] = int(memory["workingSetBytes"]["value"]) // 2**20
    return found


def measure(samples: int, interval: float) -> dict[str, int]:
    """Peak working set per component over ``samples`` readings."""
    peaks: dict[str, int] = {}
    for index in range(samples):
        for name, mib in _working_sets().items():
            peaks[name] = max(peaks.get(name, 0), mib)
        if index < samples - 1:
            time.sleep(interval)
    return peaks


def recorded_peak(name: str, image: str, measured: int) -> int:
    """What the ledger records for ``name``: the highest peak seen on this image.

    A quiet run must not lower what a busier one measured: the first `--write`
    replaced Grafana's 395 MiB with an idle 267, which would have let a limit be
    cut below what the image had been seen to use. A new image starts afresh —
    a limit chosen for one image is a guess about the next.
    """
    if not LEDGER.is_file():
        return measured
    previous = (yaml.safe_load(LEDGER.read_text(encoding="utf-8")) or {}).get("components", {}).get(name, {})
    if previous.get("image") != image:
        return measured
    return max(measured, int(previous.get("peak_mib", 0)))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--samples", type=int, default=10)
    parser.add_argument("--interval", type=float, default=3.0)
    parser.add_argument("--write", action="store_true", help="record the measurement in measured-memory.yaml")
    args = parser.parse_args(argv)

    pods = _pods()
    # A restart whose last termination was the node restarting (`Unknown`,
    # `Completed`) is not the process failing; an OOM kill or an error is.
    unhealthy = {name: state for name, state in pods.items() if not state["ready"] or state["last_reason"] in _FAILURES}
    peaks = measure(args.samples, args.interval)
    budget = yaml.safe_load(BUDGET.read_text(encoding="utf-8"))
    limits = {component["name"]: component["limit_mb"] for component in budget["components"]}

    failures = []
    for name, state in sorted(pods.items()):
        peak = peaks.get(name)
        verdict = "ok"
        if name in unhealthy:
            verdict = f"UNHEALTHY (restarts {state['restarts']}, last {state['last_reason']}, ready {state['ready']})"
            failures.append(name)
        elif peak is None or peak * HEADROOM > limits.get(name, 0):
            verdict = f"TIGHT: limit {limits.get(name)} MB < {HEADROOM} x peak"
            failures.append(name)
        shown = peak if peak is not None else "?"
        print(f"  {name:<16} peak {shown:>5} MiB  limit {limits.get(name, '?'):>5} MB  {verdict}")

    if failures:
        print(f"\n[measure] not recorded — {failures} must start cleanly inside their limits first")
        return 1
    if not args.write:
        print("\n[measure] OK — re-run with --write to record it")
        return 0

    ledger = {
        "version": 1,
        "measured_on": datetime.now(UTC).date().isoformat(),
        "method": (
            f"crictl stats working set on the kind node, peak of {args.samples} samples {args.interval:g}s apart; "
            f"the highest of every recorded run on the same image"
        ),
        "headroom": HEADROOM,
        "components": {
            name: {"image": pods[name]["image"], "peak_mib": recorded_peak(name, pods[name]["image"], peaks[name])}
            for name in sorted(pods)
        },
    }
    LEDGER.write_text(_LEDGER_HEADER + yaml.safe_dump(ledger, sort_keys=False, width=200), encoding="utf-8")
    where = LEDGER.relative_to(REPO_ROOT) if LEDGER.is_relative_to(REPO_ROOT) else LEDGER
    print(f"\n[measure] recorded {len(pods)} components in {where}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
