#!/usr/bin/env python3
"""Reports v1 CLI — read-only generator for the four canonical report
types (ADR-023 F6).

Usage
-----

    python3 scripts/generate_report.py validate <path>
    python3 scripts/generate_report.py example release  > out.json
    python3 scripts/generate_report.py example drift    > out.json
    python3 scripts/generate_report.py example training > out.json
    python3 scripts/generate_report.py example incident > out.json

Modes
-----

* ``validate`` — load a JSON file and validate it against the schema
  (lightweight in-tree check + optional jsonschema if installed).
  Exit 0 on success, 1 on any violation.
* ``example`` — emit a syntactically valid example for the chosen
  type. Useful for adopters wiring CI gates ("does my CI even know
  what a release report looks like?").

Why ``example`` instead of ``generate``
---------------------------------------

Real reports must be generated by the workflows that own the data
(release-checklist, drift-detection, retrain, incident). A generic
``generate`` here would invite the agent to invent values it does
not know — exactly the anti-pattern ADR-023 §F6 forbids. The CLI
is therefore restricted to the read-only ``validate`` and the
documentation-only ``example`` paths.

This script never writes outside the path the human passes on the
command line. It never reaches the network.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_FILE = REPO_ROOT / "templates" / "config" / "report_schema.json"

# Make `templates/service/common_utils` importable without installing a package.
sys.path.insert(0, str(REPO_ROOT / "templates" / "service"))

# pylint: disable=wrong-import-position
from common_utils.agent_context import AgentMode, Environment  # noqa: E402
from common_utils.reports import (  # noqa: E402
    DriftFeature,
    DriftPayload,
    IncidentPayload,
    QualityGate,
    ReleasePayload,
    TimelineEvent,
    TrainingPayload,
    build_drift_report,
    build_incident_report,
    build_release_report,
    build_training_report,
    load_report,
    validate_report_dict,
)


def _validate(path: Path) -> int:
    if not path.exists():
        print(f"error: file not found: {path}", file=sys.stderr)
        return 1
    try:
        doc = load_report(path)
    except (ValueError, json.JSONDecodeError) as exc:
        print(f"[FAIL] {path}: {exc}", file=sys.stderr)
        return 1

    # Optional second pass via jsonschema if available — gives more
    # specific error messages than the in-tree validator.
    try:
        import jsonschema  # type: ignore
    except ImportError:
        jsonschema = None  # type: ignore

    if jsonschema is not None:
        try:
            schema = json.loads(SCHEMA_FILE.read_text(encoding="utf-8"))
            jsonschema.validate(instance=doc, schema=schema)
        except jsonschema.ValidationError as exc:  # type: ignore[attr-defined]
            print(f"[FAIL] {path}: schema violation: {exc.message}", file=sys.stderr)
            print(f"  path: {list(exc.absolute_path)}", file=sys.stderr)
            return 1

    print(f"[ OK ] {path}")
    return 0


def _example_release() -> dict:
    payload = ReleasePayload(
        version="v0.7.0",
        commit_sha="deadbeef0000000000000000000000000000dead",
        images=("ghcr.io/example/fraud-detector@sha256:" + "a" * 64,),
        quality_gates_passed=True,
        deploy_targets=("gcp", "aws"),
        sbom_present=True,
        images_signed=True,
        adrs_since_last_release=("ADR-023",),
        drift_baseline_age_days=7,
    )
    rep = build_release_report(
        service="fraud_detector",
        generated_by="Agent-K8sBuilder",
        mode=AgentMode.CONSULT,
        environment=Environment.STAGING,
        approver="platform_engineer",
        payload=payload,
        generated_at="2026-05-03T18:00:00Z",
        report_id="release-fraud_detector-20260503T180000-0.7.0",
        links=(("PR", "https://github.com/example/repo/pull/123"),),
    )
    return rep.to_dict()


def _example_drift() -> dict:
    payload = DriftPayload(
        window_start="2026-05-01T00:00:00Z",
        window_end="2026-05-03T00:00:00Z",
        features=(
            DriftFeature(name="age", psi=0.12, threshold=0.20, breached=False),
            DriftFeature(name="amount", psi=0.34, threshold=0.20, breached=True),
        ),
        alerts_fired=("DriftPSIWarning",),
        retrain_recommendation="soft",
        root_cause_summary="Upstream amount distribution shifted after May 1 rate change.",
    )
    rep = build_drift_report(
        service="fraud_detector",
        generated_by="Agent-DriftMonitor",
        mode=AgentMode.AUTO,
        payload=payload,
        generated_at="2026-05-03T01:30:00Z",
        report_id="drift-fraud_detector-20260503T013000",
        environment=Environment.STAGING,
    )
    return rep.to_dict()


def _example_training() -> dict:
    payload = TrainingPayload(
        run_id="mlflow_abc12345",
        model_name="fraud_detector_xgb",
        metrics={"auc": 0.913, "pr_auc": 0.872, "f1": 0.84},
        quality_gates=(
            QualityGate(gate="auc>=0.85", passed=True),
            QualityGate(gate="fairness_dir>=0.80", passed=True, details="DIR=0.91"),
        ),
        promotion_state="Staging",
        fairness_dir=0.91,
    )
    rep = build_training_report(
        service="fraud_detector",
        generated_by="Agent-MLTrainer",
        mode=AgentMode.AUTO,
        payload=payload,
        generated_at="2026-05-03T15:00:00Z",
        report_id="training-fraud_detector-20260503T150000-mlflow_a",
        links=(("MLflow run", "https://mlflow.example.org/#/experiments/1/runs/abc12345"),),
    )
    return rep.to_dict()


def _example_incident() -> dict:
    payload = IncidentPayload(
        incident_id="INC-20260503001",
        severity="P2",
        detected_at="2026-05-03T14:00:00Z",
        resolved_at="2026-05-03T15:30:00Z",
        duration_minutes=90,
        root_cause="Upstream feature service returned malformed amount field after migration.",
        timeline=(
            TimelineEvent(
                timestamp="2026-05-03T14:00:00Z",
                event="latency p99 alert fired (>500ms)",
                actor="alertmanager",
            ),
            TimelineEvent(
                timestamp="2026-05-03T14:15:00Z",
                event="rollback to v0.6.5 initiated",
                actor="oncall:carol",
            ),
            TimelineEvent(
                timestamp="2026-05-03T15:30:00Z",
                event="metrics back to baseline; incident resolved",
                actor="oncall:carol",
            ),
        ),
    )
    rep = build_incident_report(
        service="fraud_detector",
        generated_by="human:carol",
        mode=AgentMode.CONSULT,
        environment=Environment.PRODUCTION,
        approver="oncall_lead",
        payload=payload,
        generated_at="2026-05-03T15:45:00Z",
        report_id="incident-fraud_detector-20260503T154500-INC-20260503001",
    )
    return rep.to_dict()


_EXAMPLES = {
    "release": _example_release,
    "drift": _example_drift,
    "training": _example_training,
    "incident": _example_incident,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_val = sub.add_parser("validate", help="validate a report JSON file")
    p_val.add_argument("path", type=Path)

    p_ex = sub.add_parser("example", help="print a syntactically valid example")
    p_ex.add_argument("type", choices=sorted(_EXAMPLES))

    args = parser.parse_args()
    if args.cmd == "validate":
        return _validate(args.path)
    if args.cmd == "example":
        doc = _EXAMPLES[args.type]()
        validate_report_dict(doc)  # belt-and-suspenders
        print(json.dumps(doc, indent=2))
        return 0
    return 2  # pragma: no cover - argparse already enforces


if __name__ == "__main__":
    raise SystemExit(main())
