#!/usr/bin/env python3
"""The README follows the shared README standard, and its status is generated.

`docs/governance/readme-standard.md` — the same file in `ml-service-template`
and here — fixes the README's sections, their order, a length budget, which
badges may appear, and a related-repositories table both READMEs carry. This
reads the README against it.

It exists because this README described the repository's first day for two
months: "Phase 0, the projects are not built yet", over three projects that
were built and in CI. Every other document here had a gate; the one every
visitor reads first had none.

The status block is not typed. It is generated from
`docs/architecture/implementation-status.md` — whose own generator verifies
each row by running its command, and whose `--check` runs in CI — and from the
audit marker in `AGENTS.md` with the committed QA-4 reports. So the README can
say only what that chain has proven, and goes red the day it stops matching.

    uv run python scripts/check_readme.py            # check (CI)
    uv run python scripts/check_readme.py --write    # regenerate the generated blocks
"""

from __future__ import annotations

import argparse
import re
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import readme_standard  # the shared half, byte-identical in both repositories
from readme_standard import RELATED_BEGIN, RELATED_END, STATUS_BEGIN, STATUS_END, _replace  # noqa: F401

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "README.md"
STANDARD = REPO_ROOT / "docs" / "governance" / "readme-standard.md"
STATUS_DOC = REPO_ROOT / "docs" / "architecture" / "implementation-status.md"
AGENTS = REPO_ROOT / "AGENTS.md"
AUDITS = REPO_ROOT / "docs" / "governance" / "qa4"
WORKFLOWS = REPO_ROOT / ".github" / "workflows"

#: Where the quick start clones this repository from, and the branch whose
#: README a reader is reading — the one CI verifies at every merge.
CLONE_URL = "https://github.com/DuqueOM/ml-platform.git"
DEFAULT_BRANCH = "main"

#: Badges that show a NUMBER, allowed only because a gate in this repository
#: already compares that number with its source — each paired with that gate.
#: None here: this repository's README states no gated count in a badge.
GATED_BADGES: tuple[tuple[re.Pattern[str], str], ...] = ()


# --- the status block: generated, never typed ------------------------------

_SUMMARY = re.compile(r"\*\*(\d+) done · (\d+) partial · (\d+) absent\*\* — of (\d+) tracked components\.")
_LAYERS = re.compile(
    r"\*\*Proven in CI: (\d+) at L1 · (\d+) at L2\.\*\* Evidence available but NOT run here: (\d+) at L3, (\d+) at L4\."
)
_PHASE = re.compile(r"^### Phase (\S+)")
_PROJECT_ROW = re.compile(r"^\| (✅|🟡|⬜) \| (L\d|—) \| projects/([\w-]+) \|")
_AUDIT_MARKER = re.compile(r"Last independent audit:\s*(\d{4}-\d{2}-\d{2})\s*\(([0-9a-f]{7,40})\)")
_STATE = {"✅": "built", "🟡": "partial", "⬜": "planned"}


def _wrap(paragraph: str) -> str:
    """Prose wrapped at the markdown line limit both repositories lint to; links are never split mid-token."""
    return textwrap.fill(paragraph, width=120, break_long_words=False, break_on_hyphens=False)


def _shown(path: Path) -> str:
    """A path as a reader finds it: relative to the repository when it is inside it."""
    return str(path.relative_to(REPO_ROOT)) if path.is_relative_to(REPO_ROOT) else str(path)


def status() -> str:
    """The README's status block, from the documents that are themselves checked."""
    document = STATUS_DOC.read_text(encoding="utf-8")
    summary, layers = _SUMMARY.search(document), _LAYERS.search(document)
    if summary is None or layers is None:
        raise ValueError(f"{_shown(STATUS_DOC)} no longer carries its generated summary lines")
    done, partial, absent, total = summary.groups()
    l1, l2, l3, l4 = layers.groups()

    projects, phase = [], "?"
    for line in document.splitlines():
        if heading := _PHASE.match(line):
            phase = heading.group(1)
        elif row := _PROJECT_ROW.match(line):
            mark, layer, name = row.groups()
            state = _STATE[mark] if mark != "⬜" else f"planned (Phase {phase})"
            projects.append(f"| `{name}` | {mark} {state} | {layer} |")
    if not projects:
        raise ValueError(f"{_shown(STATUS_DOC)} lists no projects/ component")

    marker = _AUDIT_MARKER.search(AGENTS.read_text(encoding="utf-8"))
    reports = (re.fullmatch(r"round-(\d+)\.txt", path.name) for path in AUDITS.glob("round-*.txt"))
    rounds = sorted(int(report.group(1)) for report in reports if report)
    if marker is None or not rounds:
        raise ValueError("no audit marker in AGENTS.md, or no committed QA-4 report under docs/governance/qa4/")
    cloud = "**L4 (cloud): 0** — nothing has been deployed to a cloud." if l4 == "0" else f"**L4 (cloud): {l4}.**"

    return "\n".join(
        [
            "<!-- Generated by `scripts/check_readme.py --write` from docs/architecture/implementation-status.md,",
            "     AGENTS.md and docs/governance/qa4/. Edit those, then regenerate; never edit this block. -->",
            "",
            _wrap(
                f"**{done} done · {partial} partial · {absent} absent** of {total} tracked components — see "
                f"[implementation status](docs/architecture/implementation-status.md), where every row names the "
                f"command that proves it. Proven in CI: {l1} at L1 (contract) · {l2} at L2 (component). Evidence "
                f"that needs a cluster exists for {l3} and is not run in CI. {cloud}"
            ),
            "",
            "| Project | State | Evidence layer |",
            "| --- | --- | :-: |",
            *projects,
            "",
            _wrap(
                f"Last independent audit: **QA-4 round {rounds[-1]}**, {marker.group(1)}, at `{marker.group(2)}` — "
                f"[report](docs/governance/qa4/round-{rounds[-1]}.txt)."
            ),
        ]
    )


# --- the checks: the shared half -------------------------------------------


def _holds(path: str) -> bool:
    """Whether ``path`` names a file in this checkout, relative to its root and without `..`."""
    relative = Path(path)
    if relative.is_absolute() or ".." in relative.parts:
        return False
    target = (REPO_ROOT / relative).resolve()
    return target.is_relative_to(REPO_ROOT) and target.is_file()


def repository() -> readme_standard.Repository:
    """What the quick-start rules need to know about this repository, read from it."""
    workflows = sorted(WORKFLOWS.glob("*.yml")) + sorted(WORKFLOWS.glob("*.yaml"))
    return readme_standard.Repository(
        clone_url=CLONE_URL,
        default_branch=DEFAULT_BRANCH,
        ci_requirements=readme_standard.requirements_installed_by(p.read_text(encoding="utf-8") for p in workflows),
        holds=_holds,
    )


def check(readme: str, standard: str, generated: str) -> list[str]:
    """One message per departure from the standard. Empty means the README conforms."""
    badges = tuple(pattern for pattern, _ in GATED_BADGES)
    return readme_standard.check(readme, standard, generated, badges, repository=repository())


def write(readme: str, generated: str, standard: str) -> str:
    """The README with its status block and its related-repositories table regenerated."""
    return readme_standard.write(readme, generated, standard)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="regenerate the status block and the related table")
    args = parser.parse_args(argv)

    generated = status()
    readme = README.read_text(encoding="utf-8")
    standard = STANDARD.read_text(encoding="utf-8")
    if args.write:
        updated = write(readme, generated, standard)
        if updated != readme:
            README.write_text(updated, encoding="utf-8")
            print("[readme] status block regenerated")
        readme = updated

    failures = check(readme, standard, generated)
    if failures:
        for failure in failures:
            print(f"  FAIL [readme] {failure}")
        print("\n[readme] FAILED — README.md departs from docs/governance/readme-standard.md")
        return 1
    sections = len(readme_standard.limits(standard).sections)
    print(f"[readme] OK — {sections} sections in order, status generated, within budget")
    return 0


if __name__ == "__main__":
    sys.exit(main())
