#!/usr/bin/env python3
"""Render tool-specific agentic surfaces from the canonical store.

`agentic/` is the only place policy text exists. Every supported tool gets a
generated surface so that a rule binding under one tool binds under all of
them — parity is the property this script exists to guarantee, and it is the
property that silently disappears when surfaces are maintained by hand.

Two render modes (see `agentic/manifest.yaml`):

  pointer  the surface file names its canonical source and nothing else, so it
           cannot drift by construction.
  mirror   the surface file carries the full canonical body, for tools that
           ingest contents and cannot follow a path. This CAN drift, which is
           exactly why `validate_agentic_surface.py` checks it byte for byte.

Idempotent: running twice changes nothing. Run with `--check` to fail instead
of writing, which is what CI uses.

    python scripts/sync_agentic_adapters.py
    python scripts/sync_agentic_adapters.py --check
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "agentic" / "manifest.yaml"

GENERATED_MARKER = "<!-- generated by scripts/sync_agentic_adapters.py — do not edit -->"


@dataclass(frozen=True)
class Artifact:
    """One canonical body and the identity it is published under."""

    kind: str  # rules | skills | workflows
    name: str  # stem, e.g. "11-kubernetes"
    source: Path  # canonical file
    body: str


def _load_manifest() -> dict[str, Any]:
    if not MANIFEST.is_file():
        sys.exit(f"missing manifest: {MANIFEST.relative_to(REPO_ROOT)}")
    loaded = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict), f"{MANIFEST} must be a mapping"
    return loaded


def collect(manifest: dict[str, Any]) -> list[Artifact]:
    """Read every canonical body named by the manifest's stores."""
    artifacts: list[Artifact] = []
    for kind, store in manifest["stores"].items():
        root = REPO_ROOT / store["path"]
        if not root.is_dir():
            sys.exit(f"store {kind!r} declares {store['path']}, which does not exist")
        for path in sorted(root.glob(store["glob"])):
            # A skill is a directory containing SKILL.md; its identity is the
            # directory name, not the filename, which is the same for all.
            name = path.parent.name if path.name == "SKILL.md" else path.stem
            artifacts.append(Artifact(kind=kind, name=name, source=path, body=path.read_text(encoding="utf-8")))
    return artifacts


def render_pointer(artifact: Artifact, surface: str) -> str:
    """A file that names its source and refuses to restate it."""
    rel = artifact.source.relative_to(REPO_ROOT)
    return f"""{GENERATED_MARKER}
# {artifact.name}

**Adapter surface**: `{surface}`
**Canonical source**: `{rel}`
**Authority**: `AGENTS.md` + `agentic/manifest.yaml`

Read the canonical source in full before acting. This file is a thin pointer
and deliberately contains no policy text — duplicating it here would create a
second copy that can disagree with the first.

The AUTO / CONSULT / STOP protocol in `AGENTS.md` binds on this surface exactly
as it does on every other.

To change this, edit `{rel}`, then run:

```bash
python scripts/sync_agentic_adapters.py
python scripts/validate_agentic_surface.py --strict
```
"""


_RELATIVE_LINK = re.compile(r"\]\((\.{1,2}/[^)\s]+)\)")


def rewrite_relative_links(body: str, source_dir: Path, target_dir: Path) -> str:
    """Re-express every relative link for a file that moved to another depth.

    The mirror used to copy the body verbatim, and the bodies live deeper than
    their mirrors: a skill is `agentic/skills/<id>/SKILL.md` (three levels down)
    and its mirror is `.devin/skills/<id>.md` (two). So `../../../docs/...`
    resolved from the canonical file and pointed one level above the repository
    from the mirror — five broken links, in generated output, that nothing
    noticed because the coherence gate resolves ADR NUMBERS and never follows
    an href.

    Resolved and re-expressed rather than counted: computing the depth
    difference and slicing `../` prefixes gets the common case right and fails
    on a link that walks back down (`../foo/../bar`). Round-tripping through
    the repository-relative path cannot.

    Args:
        body: The canonical markdown.
        source_dir: Directory the canonical file lives in.
        target_dir: Directory the mirror will live in.

    Returns:
        The body with every relative link valid from ``target_dir``.
    """
    if source_dir == target_dir:
        return body

    def _fix(match: re.Match[str]) -> str:
        link = match.group(1)
        path, _, anchor = link.partition("#")
        resolved = (source_dir / path).resolve()
        try:
            rewritten = os.path.relpath(resolved, target_dir)
        except ValueError:  # pragma: no cover — different drives, Windows only
            return match.group(0)
        return f"]({rewritten}{'#' + anchor if anchor else ''})"

    return _RELATIVE_LINK.sub(_fix, body)


def render_mirror(artifact: Artifact, surface: str) -> str:
    """A full copy, for tools that cannot follow a pointer."""
    rel = artifact.source.relative_to(REPO_ROOT)
    return f"""{GENERATED_MARKER}
<!-- surface: {surface} | canonical: {rel} -->
<!-- This is a MIRROR. Edit the canonical source, never this file. -->

{artifact.body}"""


def target_path(artifact: Artifact, surface_cfg: dict[str, Any]) -> Path:
    subdir = str(surface_cfg["layout"][artifact.kind])
    ext = str(surface_cfg["extension"])
    return REPO_ROOT / str(surface_cfg["root"]) / subdir / f"{artifact.name}{ext}"


def sync(check_only: bool) -> int:
    manifest = _load_manifest()
    artifacts = collect(manifest)

    stale: list[str] = []
    written = 0

    for surface, cfg in manifest["surfaces"].items():
        renderer = render_mirror if cfg["mode"] == "mirror" else render_pointer
        expected: set[Path] = set()

        for artifact in artifacts:
            path = target_path(artifact, cfg)
            expected.add(path)
            content = renderer(artifact, surface)
            if cfg["mode"] == "mirror":
                content = rewrite_relative_links(content, artifact.source.parent, path.parent)

            current = path.read_text(encoding="utf-8") if path.is_file() else None
            if current == content:
                continue
            if check_only:
                state = "missing" if current is None else "stale"
                stale.append(f"{state}: {path.relative_to(REPO_ROOT)}")
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            written += 1

        # Remove orphans: a surface file whose canonical source was deleted or
        # renamed. Left alone, it becomes policy nobody can find the origin of.
        for subdir in set(cfg["layout"].values()):
            directory = REPO_ROOT / cfg["root"] / subdir
            if not directory.is_dir():
                continue
            for path in sorted(directory.glob(f"*{cfg['extension']}")):
                if path in expected:
                    continue
                if check_only:
                    stale.append(f"orphan: {path.relative_to(REPO_ROOT)}")
                else:
                    path.unlink()
                    written += 1

    if check_only:
        if stale:
            print("[sync] surfaces are OUT OF DATE\n")
            for item in stale:
                print(f"  {item}")
            print(f"\n{len(stale)} file(s). Run: python scripts/sync_agentic_adapters.py")
            return 1
        print(f"[sync] OK — {len(artifacts)} artifacts, {len(manifest['surfaces'])} surfaces, all current")
        return 0

    print(
        f"[sync] rendered {len(artifacts)} artifacts across "
        f"{len(manifest['surfaces'])} surfaces ({written} file(s) changed)"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if surfaces are out of date instead of writing")
    parser.add_argument("--clean", action="store_true", help="remove every generated surface root first")
    args = parser.parse_args()

    if args.clean and not args.check:
        for surface_cfg in _load_manifest()["surfaces"].values():
            shutil.rmtree(REPO_ROOT / surface_cfg["root"], ignore_errors=True)

    return sync(check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
