#!/usr/bin/env python3
"""Render tool-specific agentic surfaces from the canonical store.

`agentic/` is the only place policy text exists. Every supported tool gets a
generated surface so that a rule binding under one tool binds under all of
them — parity is the property this script exists to guarantee, and it is the
property that silently disappears when surfaces are maintained by hand.

Two render modes (see `agentic/manifest.yaml`):

  pointer  the surface file names its canonical source and nothing else, so it
           cannot drift by construction.
  mirror   the surface file carries the full canonical body, for tools that
           ingest contents and cannot follow a path. This CAN drift, which is
           exactly why `validate_agentic_surface.py` checks it byte for byte.

The context files (`AGENT_CONTEXT.md` and one `.<tool>_context.md` per surface)
are rendered here too, for the reason the rest of this script exists: they
describe a generated tree — which directory holds what, in which mode, how
many of each — and a hand-written description of generated output drifts the
moment the tree changes. Upstream hand-maintains its five and they are already
wrong about their own file counts. Every derivable fact here is derived; the
tool-specific prose that is NOT derivable is stored as data in the manifest, so
it still has exactly one home.

Idempotent: running twice changes nothing. Run with `--check` to fail instead
of writing, which is what CI uses.

    python scripts/sync_agentic_adapters.py
    python scripts/sync_agentic_adapters.py --check
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "agentic" / "manifest.yaml"

GENERATED_MARKER = "<!-- generated by scripts/sync_agentic_adapters.py — do not edit -->"


@dataclass(frozen=True)
class Artifact:
    """One canonical body and the identity it is published under."""

    kind: str  # rules | skills | workflows
    name: str  # stem, e.g. "11-kubernetes"
    source: Path  # canonical file
    body: str


def _load_manifest() -> dict[str, Any]:
    if not MANIFEST.is_file():
        sys.exit(f"missing manifest: {MANIFEST.relative_to(REPO_ROOT)}")
    loaded = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict), f"{MANIFEST} must be a mapping"
    return loaded


def collect(manifest: dict[str, Any]) -> list[Artifact]:
    """Read every canonical body named by the manifest's stores."""
    artifacts: list[Artifact] = []
    for kind, store in manifest["stores"].items():
        root = REPO_ROOT / store["path"]
        if not root.is_dir():
            sys.exit(f"store {kind!r} declares {store['path']}, which does not exist")
        for path in sorted(root.glob(store["glob"])):
            # A skill is a directory containing SKILL.md; its identity is the
            # directory name, not the filename, which is the same for all.
            name = path.parent.name if path.name == "SKILL.md" else path.stem
            artifacts.append(Artifact(kind=kind, name=name, source=path, body=path.read_text(encoding="utf-8")))
    return artifacts


def front_matter(text: str) -> dict[str, Any]:
    """A canonical body's leading YAML front-matter, or an empty mapping."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    loaded = yaml.safe_load(text[3:end])
    return loaded if isinstance(loaded, dict) else {}


def render_front_matter(artifact: Artifact) -> str:
    """The front-matter a tool reads to list and route an artifact.

    A skill gets `name` and `description`, the two fields every tool that
    discovers skills requires; its declared mode is appended to the
    description, because the description is the one field a tool shows before
    the body is read. A command gets `description` only — Claude rejects
    `name` there. Nothing else is copied: `allowed-tools` in particular stays
    in the canonical body, where pre-approving a tool is a reviewed decision
    rather than a side effect of rendering.
    """
    declared = front_matter(artifact.body)
    description = str(declared.get("description") or "").strip()
    if not description:
        sys.exit(
            f"{artifact.source.relative_to(REPO_ROOT)} has no `description:` front-matter, and a surface lists "
            "it by that field — without it the tool falls back to the pointer's first line"
        )
    lines = ["---"]
    if artifact.kind == "skills":
        lines.append(f"name: {artifact.name}")
        if declared.get("mode"):
            description = f"{description} (Mode: {declared['mode']})"
    lines += [f"description: {json.dumps(description, ensure_ascii=False)}", "---", ""]
    return "\n".join(lines)


def render_pointer(artifact: Artifact, surfaces: list[str], with_front_matter: bool) -> str:
    """A file that names its source and refuses to restate it."""
    rel = artifact.source.relative_to(REPO_ROOT)
    head = render_front_matter(artifact) if with_front_matter else ""
    named = ", ".join(f"`{surface}`" for surface in surfaces)
    return f"""{head}{GENERATED_MARKER}
# {artifact.name}

**Adapter surface{"s" if len(surfaces) > 1 else ""}**: {named}
**Canonical source**: `{rel}`
**Authority**: `AGENTS.md` + `agentic/manifest.yaml`

Read the canonical source in full before acting. This file is a thin pointer
and deliberately contains no policy text — duplicating it here would create a
second copy that can disagree with the first.

The AUTO / CONSULT / STOP protocol in `AGENTS.md` binds on this surface exactly
as it does on every other.

To change this, edit `{rel}`, then run:

```bash
python scripts/sync_agentic_adapters.py
python scripts/validate_agentic_surface.py --strict
```
"""


_RELATIVE_LINK = re.compile(r"\]\((\.{1,2}/[^)\s]+)\)")


def rewrite_relative_links(body: str, source_dir: Path, target_dir: Path) -> str:
    """Re-express every relative link for a file that moved to another depth.

    The mirror used to copy the body verbatim, and the bodies live deeper than
    their mirrors: a skill is `agentic/skills/<id>/SKILL.md` (three levels down)
    and its mirror is `.devin/skills/<id>.md` (two). So `../../../docs/...`
    resolved from the canonical file and pointed one level above the repository
    from the mirror — five broken links, in generated output, that nothing
    noticed because the coherence gate resolves ADR NUMBERS and never follows
    an href.

    Resolved and re-expressed rather than counted: computing the depth
    difference and slicing `../` prefixes gets the common case right and fails
    on a link that walks back down (`../foo/../bar`). Round-tripping through
    the repository-relative path cannot.

    Args:
        body: The canonical markdown.
        source_dir: Directory the canonical file lives in.
        target_dir: Directory the mirror will live in.

    Returns:
        The body with every relative link valid from ``target_dir``.
    """
    if source_dir == target_dir:
        return body

    def _fix(match: re.Match[str]) -> str:
        link = match.group(1)
        path, _, anchor = link.partition("#")
        resolved = (source_dir / path).resolve()
        try:
            rewritten = os.path.relpath(resolved, target_dir)
        except ValueError:  # pragma: no cover — different drives, Windows only
            return match.group(0)
        return f"]({rewritten}{'#' + anchor if anchor else ''})"

    return _RELATIVE_LINK.sub(_fix, body)


def render_mirror(artifact: Artifact, surfaces: list[str]) -> str:
    """A full copy, for tools that cannot follow a pointer."""
    rel = artifact.source.relative_to(REPO_ROOT)
    return f"""{GENERATED_MARKER}
<!-- surface: {", ".join(surfaces)} | canonical: {rel} -->
<!-- This is a MIRROR. Edit the canonical source, never this file. -->

{artifact.body}"""


def _counts(artifacts: list[Artifact], kinds: list[str]) -> dict[str, int]:
    """How many canonical bodies exist per kind, in the manifest's order."""
    return {kind: sum(1 for a in artifacts if a.kind == kind) for kind in kinds}


def _load_registry(manifest: dict[str, Any]) -> dict[str, Any]:
    """The MCP registry, so per-surface MCP facts are read rather than restated."""
    rel = manifest["context"].get("mcp_registry")
    if not rel:
        return {}
    path = REPO_ROOT / str(rel)
    if not path.is_file():
        sys.exit(f"context declares mcp_registry {rel}, which does not exist")
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    return loaded if isinstance(loaded, dict) else {}


_MODE_PROSE = {
    "pointer": (
        "is rendered in **pointer** mode: each file names its canonical body under `agentic/` and restates none of "
        "it, so what you read there is an address and never the policy itself. Act on the canonical body, not on "
        "the pointer"
    ),
    "mirror": (
        "is rendered in **mirror** mode: each file carries the full canonical body, because this tool ingests "
        "directory contents and cannot follow a path. What you read there is a copy — correct until it is not, "
        "which is why it is the one surface checked byte for byte"
    ),
}


def _mcp_lines(surface: str, registry: dict[str, Any]) -> list[str]:
    """The MCP facts that differ per tool: where its config lives, what it must confirm."""
    surfaces = registry.get("surfaces") or {}
    if surface not in surfaces:
        sys.exit(
            f"surface {surface!r} has no entry under `surfaces:` in the MCP registry — its config path is undeclared"
        )
    entry = surfaces[surface] or {}
    example = entry.get("committed_example")
    confirm = sorted(
        name
        for name, spec in (registry.get("mcps") or {}).items()
        if ((spec or {}).get("install_mode") or {}).get(surface) == "user_confirmed"
    )
    return [
        f"- Config path for this surface: `{entry.get('config_path', 'undeclared')}` — never committed.",
        f"- Committed example: {f'`{example}`' if example else 'none — there is nothing tool-specific to template.'}",
        "- Servers this surface may not install without an explicit human decision: "
        + (", ".join(f"`{name}`" for name in confirm) if confirm else "none are marked `user_confirmed` here")
        + ".",
        "- Nothing is installed automatically. `agentic/mcp_registry.yaml` declares each server's ceiling risk mode, "
        "and adding one is a supply-chain decision made on the repository's behalf.",
    ]


def render_shared_context(manifest: dict[str, Any], artifacts: list[Artifact]) -> str:
    """`AGENT_CONTEXT.md` — the inventory every tool shares, and no policy."""
    kinds = list(manifest["stores"])
    counts = _counts(artifacts, kinds)
    stores = "\n".join(f"| {kind} | `{manifest['stores'][kind]['path']}` | {counts[kind]} |" for kind in kinds)
    surfaces = "\n".join(
        f"| `{cfg['root']}/` | {cfg['mode']} | `{cfg['context']['path']}` |" for cfg in manifest["surfaces"].values()
    )
    return f"""{GENERATED_MARKER}
# Agent context

Orientation for an agent that has just attached to this repository: what the
agentic surface contains, which directory your tool reads, and which parts of
the tree are generated. It is deliberately **not** policy — [AGENTS.md](AGENTS.md)
is the authority, and if the two ever disagree, this file is the defect.

Generated from `agentic/manifest.yaml`. Every count below is taken from the
filesystem at render time, so it cannot quietly become false the way a
hand-written inventory of a generated tree does.

## Read in this order

- [AGENTS.md](AGENTS.md) — the operating constitution: invariants, the
  AUTO / CONSULT / STOP protocol, and the pre-commit cadence.
- [CONTRIBUTING.md](CONTRIBUTING.md) — the cadence in order, why staging comes
  before regenerating, and how a change is classified.
- [llms.txt](llms.txt) — what the repository contains, in one page.
- [docs/architecture/implementation-status.md](docs/architecture/implementation-status.md)
  — what exists, derived from the filesystem rather than declared.

## The canonical store

Policy text exists in `agentic/` and nowhere else.

| Kind | Canonical path | Count |
| --- | --- | --- |
{stores}

## The surfaces rendered from it

| Directory | Mode | Context file |
| --- | --- | --- |
{surfaces}

Each surface publishes every canonical body, because a rule that binds under
one tool has to bind under all of them — parity disappears one file at a time,
and `validate_agentic_surface.py` exists to notice.

## Commands

```bash
python scripts/sync_agentic_adapters.py              # render every surface
python scripts/sync_agentic_adapters.py --check      # fail if stale (CI)
python scripts/validate_agentic_surface.py --strict   # parity + mode integrity
```

## What this file is not

- Not policy: modes, invariants and anti-patterns live in `AGENTS.md`.
- Not a changelog: that is `CHANGELOG.md`.
- Not a status report: `docs/architecture/implementation-status.md` derives one.
- Not editable. Change `agentic/manifest.yaml` or the renderer, then re-render.
"""


def render_surface_context(
    surface: str,
    cfg: dict[str, Any],
    manifest: dict[str, Any],
    artifacts: list[Artifact],
    registry: dict[str, Any],
) -> str:
    """`.<tool>_context.md` — only what differs for one tool."""
    ctx = cfg["context"]
    kinds = list(manifest["stores"])
    counts = _counts(artifacts, kinds)
    layout = "\n".join(
        f"| {kind} | `{cfg['layout'][kind].replace('{name}', '<id>')}` | {counts[kind]} |" for kind in kinds
    )
    discovery = "\n".join(f"- {item}" for item in ctx["discovery"])
    mcp = "\n".join(_mcp_lines(surface, registry))
    return f"""{GENERATED_MARKER}
# {ctx["tool"]} context

Read [AGENT_CONTEXT.md](AGENT_CONTEXT.md) first — it holds what is true for
every tool — and [AGENTS.md](AGENTS.md) for the authority. This file carries
only what is specific to {ctx["tool"]} in this repository.

Generated from `agentic/manifest.yaml`; an edit here survives until the next
render and no longer.

## Your surface

`{cfg["root"]}/` {_MODE_PROSE[cfg["mode"]]}.

| Kind | Where | Files |
| --- | --- | --- |
{layout}

## What that means when you work here

{discovery}

## MCP

{mcp}

## The mode contract

Every operation carries AUTO, CONSULT or STOP — the three are defined in
[CONTRIBUTING.md](CONTRIBUTING.md#auto-consult-stop) and mapped operation by
operation in [AGENTS.md](AGENTS.md#agent-behavior-protocol). The mode is a
property of the operation, not of the tool running it and not of your
confidence in it: the same procedure carries the same mode here as on every
other surface, and a surface that appears to weaken one has drifted.

## Editing

Never edit a file under `{cfg["root"]}/`, and never edit this file. Edit the
canonical body under `agentic/`, then:

```bash
python scripts/sync_agentic_adapters.py
python scripts/validate_agentic_surface.py --strict
```
"""


def context_outputs(manifest: dict[str, Any], artifacts: list[Artifact]) -> dict[Path, str]:
    """Every context file the manifest declares, rendered.

    A surface with no `context:` block is a failure rather than a skip: a tool
    that reaches this repository with no orientation is the parity hole this
    whole mechanism exists to close, and skipping it silently is how it opens.
    """
    declared = manifest.get("context")
    if not declared:
        return {}
    registry = _load_registry(manifest)
    outputs = {REPO_ROOT / str(declared["shared"]): render_shared_context(manifest, artifacts)}
    for surface, cfg in manifest["surfaces"].items():
        if "context" not in cfg:
            sys.exit(f"surface {surface!r} declares no context file, but `context:` is configured for the manifest")
        outputs[REPO_ROOT / str(cfg["context"]["path"])] = render_surface_context(
            surface, cfg, manifest, artifacts, registry
        )
    return outputs


def target_path(artifact: Artifact, surface_cfg: dict[str, Any]) -> Path:
    """Where one surface publishes one artifact: its layout pattern, filled in."""
    return REPO_ROOT / str(surface_cfg["layout"][artifact.kind]).replace("{name}", artifact.name)


def layout_bases(manifest: dict[str, Any]) -> set[Path]:
    """Every directory a layout pattern renders into — the part before `{name}`.

    Everything under one of these is generated, so anything there that the
    render did not produce is an orphan. Scanning by directory rather than by
    the pattern's glob is what removes a file left at an OLD layout: the flat
    `.claude/skills/<id>.md` files matched no pattern once skills became
    directories, and would otherwise have stayed forever.
    """
    return {
        REPO_ROOT / pattern.split("{name}")[0]
        for cfg in manifest["surfaces"].values()
        for pattern in cfg["layout"].values()
    }


def render_all(manifest: dict[str, Any], artifacts: list[Artifact]) -> dict[Path, str]:
    """Every surface file, keyed by path. A path two surfaces share is rendered once.

    Sharing is only coherent when both surfaces would write the same bytes, so a
    shared path whose surfaces disagree on render mode or front-matter is a
    manifest error rather than a last-writer-wins race.
    """
    claims: dict[Path, list[tuple[str, Artifact, dict[str, Any]]]] = {}
    for surface, cfg in manifest["surfaces"].items():
        for artifact in artifacts:
            claims.setdefault(target_path(artifact, cfg), []).append((surface, artifact, cfg))

    outputs: dict[Path, str] = {}
    for path, sharing in claims.items():
        surfaces = [surface for surface, _, _ in sharing]
        _, artifact, cfg = sharing[0]
        with_front_matter = artifact.kind in cfg.get("front_matter", [])
        for surface, other, other_cfg in sharing[1:]:
            if (
                other.source != artifact.source
                or other_cfg["mode"] != cfg["mode"]
                or (artifact.kind in other_cfg.get("front_matter", [])) != with_front_matter
            ):
                sys.exit(
                    f"{path.relative_to(REPO_ROOT)} is claimed by {surfaces[0]!r} and {surface!r}, which would render "
                    "it differently — a shared path needs the same source, mode and front-matter on every surface"
                )
        if cfg["mode"] == "mirror":
            mirrored = render_mirror(artifact, surfaces)
            outputs[path] = rewrite_relative_links(mirrored, artifact.source.parent, path.parent)
        else:
            outputs[path] = render_pointer(artifact, surfaces, with_front_matter)
    return outputs


def _surface_roots(manifest: dict[str, Any]) -> set[Path]:
    return {REPO_ROOT / str(cfg["root"]) for cfg in manifest["surfaces"].values()}


def orphans(manifest: dict[str, Any], outputs: dict[Path, str]) -> list[Path]:
    """Generated files the current render does not produce.

    Two nets, because a layout change leaves files in two kinds of place.
    Everything under a layout directory is generated, so anything there the
    render did not write is an orphan. A directory a layout STOPPED using is
    no longer a layout directory — `.cursor/skills/` once skills moved to
    `.agents/skills/` — so the surface roots are searched too, for files that
    carry the generated marker. The marker is what keeps a committed,
    hand-written file such as `.codex/mcp.example.json` out of it.
    """
    found: set[Path] = set()
    for base in layout_bases(manifest):
        if base.is_dir():
            found.update(p for p in base.rglob("*") if p.is_file())
    for root in _surface_roots(manifest):
        if root.is_dir():
            found.update(
                p for p in root.rglob("*") if p.is_file() and GENERATED_MARKER in p.read_text(encoding="utf-8")
            )
    return sorted(p for p in found if p not in outputs)


def _remove_empty_directories(manifest: dict[str, Any]) -> None:
    for top in layout_bases(manifest) | _surface_roots(manifest):
        if top.is_dir():
            for directory in sorted((d for d in top.rglob("*") if d.is_dir()), reverse=True):
                if not any(directory.iterdir()):
                    directory.rmdir()


def sync(check_only: bool) -> int:
    manifest = _load_manifest()
    artifacts = collect(manifest)
    outputs = render_all(manifest, artifacts)

    stale: list[str] = []
    written = 0

    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        if check_only:
            state = "missing" if current is None else "stale"
            stale.append(f"{state}: {path.relative_to(REPO_ROOT)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written += 1

    # Remove orphans: a surface file whose canonical source was deleted or
    # renamed, or that sits at a layout the manifest no longer uses. Left alone,
    # it becomes policy nobody can find the origin of.
    for path in orphans(manifest, outputs):
        if check_only:
            stale.append(f"orphan: {path.relative_to(REPO_ROOT)}")
        else:
            path.unlink()
            written += 1
    if not check_only:
        _remove_empty_directories(manifest)

    # Context files last: they REPORT the surface inventory, so rendering them
    # before the artifacts would describe the tree as it was, not as it is.
    # This is the wire the renderers were written for and were missing — 212
    # lines of correct code that emitted nothing, which lints clean and looks
    # finished.
    for path, content in context_outputs(manifest, artifacts).items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        if check_only:
            stale.append(f"{'missing' if current is None else 'stale'}: {path.relative_to(REPO_ROOT)}")
            continue
        path.write_text(content, encoding="utf-8")
        written += 1

    if check_only:
        if stale:
            print("[sync] surfaces are OUT OF DATE\n")
            for item in stale:
                print(f"  {item}")
            print(f"\n{len(stale)} file(s). Run: python scripts/sync_agentic_adapters.py")
            return 1
        print(f"[sync] OK — {len(artifacts)} artifacts, {len(manifest['surfaces'])} surfaces, all current")
        return 0

    print(
        f"[sync] rendered {len(artifacts)} artifacts across "
        f"{len(manifest['surfaces'])} surfaces ({written} file(s) changed)"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if surfaces are out of date instead of writing")
    parser.add_argument("--clean", action="store_true", help="remove every generated surface directory first")
    args = parser.parse_args()

    # The layout directories, not the surface roots: `.codex/` also holds the
    # committed `mcp.example.json`, which nothing renders, and removing the
    # whole root deleted it.
    if args.clean and not args.check:
        for base in layout_bases(_load_manifest()):
            shutil.rmtree(base, ignore_errors=True)

    return sync(check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
