#!/usr/bin/env python3
"""Validate the agentic surface: parity, provenance and mode integrity.

`sync_agentic_adapters.py` renders the surfaces; this checks that what exists
is coherent. The two are deliberately separate — a renderer that also validates
its own output can only ever confirm its own assumptions.

Checks:

  V1  Every canonical body is published to every surface — parity is the whole
      point of supporting four tools, and it disappears one file at a time.
  V2  Every skill has front-matter naming it, describing it, and declaring the
      AUTO/CONSULT/STOP mode of its operations. A skill with no declared mode
      is a skill whose risk nobody assessed.
  V3  No surface DE-ESCALATES a mode relative to its canonical body. A mirror
      that turns a STOP into a CONSULT is the most dangerous drift possible.
  V4  Mirror surfaces match their canonical body exactly.
  V5  Pointer surfaces contain no policy text — only the pointer.
  V6  Every rule declares its authority, and it resolves.
  V7  Every artifact is where its TOOL looks for it, with the front-matter the
      tool requires. V1 compares the surfaces with the manifest; V7 compares
      them with the tools, from a table this file keeps apart from the
      manifest. Without it, a manifest naming the wrong place passed V1 by
      construction: all 29 skills sat where Claude Code never looks, and every
      check here stayed green (QA-4 round twelve, P0-1).

Exit 1 on any failure. `--strict` additionally fails on warnings.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import yaml
from sync_agentic_adapters import rewrite_relative_links

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "agentic" / "manifest.yaml"
GENERATED_MARKER = "<!-- generated by scripts/sync_agentic_adapters.py — do not edit -->"

failures: list[str] = []
warnings: list[str] = []
notes: list[str] = []


def fail(check: str, msg: str) -> None:
    failures.append(f"[{check}] {msg}")


def warn(check: str, msg: str) -> None:
    warnings.append(f"[{check}] {msg}")


def ok(check: str, msg: str) -> None:
    """Record a passing check.

    Silently skipped when this check has already failed: a gate that prints
    both `ok` and `FAIL` for the same run is contradictory evidence, and a
    reader has to guess which line is authoritative.
    """
    if any(f.startswith(f"[{check}]") for f in failures):
        return
    notes.append(f"[{check}] {msg}")


def _front_matter(text: str) -> dict[str, Any] | None:
    """Parse leading YAML front-matter, or None when absent/invalid."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    try:
        parsed = yaml.safe_load(text[3:end])
    except yaml.YAMLError:
        return None
    return parsed if isinstance(parsed, dict) else None


def _modes_in(text: str, modes: list[str]) -> set[str]:
    """Modes explicitly asserted in a body, ignoring prose mentions.

    Matches the forms the surfaces actually use — a table cell, a bolded
    token, or a `mode:` key — so that the word "stop" in an English sentence
    is not mistaken for a STOP declaration.
    """
    found: set[str] = set()
    for mode in modes:
        pattern = rf"(\*\*{mode}\*\*|`{mode}`|^mode:.*\b{mode}\b|\|\s*{mode}\s*\|)"
        if re.search(pattern, text, re.MULTILINE):
            found.add(mode)
    return found


# What each tool discovers, from its own documentation, checked 2026-09-23:
#   Claude Code  https://code.claude.com/docs/en/skills — `.claude/skills/<name>/SKILL.md`;
#                commands `.claude/commands/<name>.md`, listed by `description`.
#   Cursor       https://cursor.com/docs/skills — `.cursor/skills/` or
#                `.agents/skills/<name>/SKILL.md`, `name` must equal the folder;
#                commands are plain markdown in `.cursor/commands/`.
#   Codex        https://learn.chatgpt.com/docs/build-skills — `.agents/skills/<name>/SKILL.md`
#                from the working directory up to the repository root, and nowhere
#                else in a repository; `name` and `description` required.
# Deliberately NOT derived from `agentic/manifest.yaml`: this is the other side
# of the comparison. A kind absent here is one whose discovery this repository
# does not claim — rules everywhere, and every Devin path, reach the agent
# because AGENTS.md names them, not because a tool indexed them.
DISCOVERY: dict[str, dict[str, tuple[tuple[str, ...], tuple[str, ...]]]] = {
    "claude": {
        "skills": ((".claude/skills/{name}/SKILL.md",), ("name", "description")),
        "workflows": ((".claude/commands/{name}.md",), ("description",)),
    },
    "cursor": {
        "skills": ((".cursor/skills/{name}/SKILL.md", ".agents/skills/{name}/SKILL.md"), ("name", "description")),
        "workflows": ((".cursor/commands/{name}.md",), ()),
    },
    "codex": {
        "skills": ((".agents/skills/{name}/SKILL.md",), ("name", "description")),
    },
}
# The open Agent Skills limit, which the three tools above share.
MAX_DESCRIPTION = 1024


def surface_path(cfg: dict[str, Any], kind: str, name: str) -> Path:
    """Where the manifest says one surface publishes one artifact."""
    return REPO_ROOT / str(cfg["layout"][kind]).replace("{name}", name)


def _layout_regex(pattern: str) -> re.Pattern[str]:
    return re.compile(re.escape(pattern).replace(re.escape("{name}"), "([^/]+)") + "$")


def collect_canonical(manifest: dict[str, Any]) -> dict[str, dict[str, Path]]:
    out: dict[str, dict[str, Path]] = {}
    for kind, store in manifest["stores"].items():
        root = REPO_ROOT / store["path"]
        entries: dict[str, Path] = {}
        for path in sorted(root.glob(store["glob"])):
            name = path.parent.name if path.name == "SKILL.md" else path.stem
            entries[name] = path
        out[kind] = entries
    return out


def check_parity(manifest: dict[str, Any], canonical: dict[str, dict[str, Path]]) -> None:
    """V1 — every canonical body reaches every surface, and nothing else is there."""
    for surface, cfg in manifest["surfaces"].items():
        for kind, entries in canonical.items():
            pattern = str(cfg["layout"][kind])
            base = REPO_ROOT / pattern.split("{name}")[0]
            matcher = _layout_regex(pattern)
            present: set[str] = set()
            if base.is_dir():
                for path in sorted(p for p in base.rglob("*") if p.is_file()):
                    rel = path.relative_to(REPO_ROOT).as_posix()
                    match = matcher.match(rel)
                    if match:
                        present.add(match.group(1))
                    elif not any(_layout_regex(str(p)).match(rel) for p in cfg["layout"].values()):
                        fail("V1", f"{surface}: {rel} is not at a path the {kind} layout produces")
            for name in sorted(set(entries) - present):
                fail("V1", f"{surface}: {kind}/{name} is not published")
            for name in sorted(present - set(entries)):
                fail("V1", f"{surface}: {kind}/{name} has no canonical source (orphan)")
    total = sum(len(v) for v in canonical.values())
    ok("V1", f"{total} artifacts x {len(manifest['surfaces'])} surfaces")


def check_skill_front_matter(canonical: dict[str, dict[str, Path]], modes: list[str]) -> None:
    """V2 — a skill declares what it is and the mode its operations carry."""
    for name, path in canonical.get("skills", {}).items():
        text = path.read_text(encoding="utf-8")
        fm = _front_matter(text)
        if fm is None:
            fail("V2", f"skill {name} has no parseable front-matter")
            continue
        for key in ("name", "description"):
            if not fm.get(key):
                fail("V2", f"skill {name} front-matter is missing {key!r}")
        if fm.get("name") and fm["name"] != name:
            fail("V2", f"skill {name} declares name {fm['name']!r} — must match its directory")
        declared = str(fm.get("mode", ""))
        if not _modes_in(declared, modes) and not _modes_in(text, modes):
            fail("V2", f"skill {name} declares no AUTO/CONSULT/STOP mode anywhere")
    ok("V2", f"{len(canonical.get('skills', {}))} skills carry front-matter and a declared mode")


def check_no_de_escalation(manifest: dict[str, Any], canonical: dict[str, dict[str, Path]], modes: list[str]) -> None:
    """V3 — a surface may never weaken a mode its canonical body asserts.

    The dangerous direction is one-way: a mirror that drops a STOP has removed
    a control while still looking like the real thing.
    """
    rank = {m: i for i, m in enumerate(modes)}
    for surface, cfg in manifest["surfaces"].items():
        if cfg["mode"] != "mirror":
            continue  # pointers carry no policy text to weaken
        for kind, entries in canonical.items():
            for name, source in entries.items():
                target = surface_path(cfg, kind, name)
                if not target.is_file():
                    continue  # already reported by V1
                want = _modes_in(source.read_text(encoding="utf-8"), modes)
                got = _modes_in(target.read_text(encoding="utf-8"), modes)
                lost = {m for m in want - got if rank[m] > 0}
                if lost:
                    fail("V3", f"{surface}: {kind}/{name} drops {sorted(lost)} present in canonical")
    ok("V3", "no surface de-escalates a mode")


def check_mirror_fidelity(manifest: dict[str, Any], canonical: dict[str, dict[str, Path]]) -> None:
    """V4 — a mirror carries its canonical body, transformed only as the generator transforms it.

    This asserted byte-identity until the generator started rewriting relative
    links: a mirror sits at a different depth than its source, so a body copied
    verbatim carried `../../../docs/...` from three levels down into a file two
    levels down, and pointed above the repository root.

    The fix collided with this check, which is the useful part. V4 and the
    generator were modelling the same relationship independently, so a change
    to one made the other wrong — two definitions of "what a mirror should
    contain", which is the drift the whole agentic surface exists to prevent,
    reproduced inside the checks that guard it.

    So V4 no longer describes the transformation. It APPLIES the generator's
    own function and compares, which means a future transformation cannot make
    this check wrong; it can only make it check the new thing.
    """
    for surface, cfg in manifest["surfaces"].items():
        if cfg["mode"] != "mirror":
            continue
        drifted = 0
        for kind, entries in canonical.items():
            for name, source in entries.items():
                target = surface_path(cfg, kind, name)
                if not target.is_file():
                    continue
                expected = rewrite_relative_links(source.read_text(encoding="utf-8"), source.parent, target.parent)
                if expected not in target.read_text(encoding="utf-8"):
                    fail("V4", f"{surface}: {kind}/{name} body drifted from canonical")
                    drifted += 1
        if not drifted:
            ok("V4", f"{surface}: all mirrored bodies match canonical, links rewritten for depth")


def check_pointer_purity(manifest: dict[str, Any]) -> None:
    """V5 — a pointer surface restates no policy.

    A pointer that grows policy text has become a second source of truth, and
    the two will disagree. Size is a crude proxy, and a deliberate one: any
    pointer materially longer than the template is carrying something.
    """
    for _surface, cfg in manifest["surfaces"].items():
        if cfg["mode"] != "pointer":
            continue
        for pattern in cfg["layout"].values():
            for path in sorted(REPO_ROOT.glob(str(pattern).replace("{name}", "*"))):
                text = path.read_text(encoding="utf-8")
                if GENERATED_MARKER not in text:
                    fail("V5", f"{path.relative_to(REPO_ROOT)} is not generated — hand-edited surface file")
                if len(text.splitlines()) > 40:
                    fail("V5", f"{path.relative_to(REPO_ROOT)} is too long for a pointer — it restates policy")
    ok("V5", "pointer surfaces contain no policy text")


def check_rule_authority(canonical: dict[str, dict[str, Path]], manifest: dict[str, Any]) -> None:
    """V6 — a rule names its authority, and the authority exists."""
    known = {v["path"] for v in manifest["canonical"].values()}
    for name, path in canonical.get("rules", {}).items():
        text = path.read_text(encoding="utf-8")
        refs = re.findall(r"(AGENTS\.md|docs/decisions/ADR-\d{3}[a-z0-9-]*\.md)", text)
        if not refs:
            warn("V6", f"rule {name} cites no authority (AGENTS.md or an ADR)")
            continue
        for ref in set(refs):
            if ref in known or ref == "AGENTS.md":
                continue
            if not (REPO_ROOT / ref).is_file():
                fail("V6", f"rule {name} cites {ref}, which does not exist")
    ok("V6", f"{len(canonical.get('rules', {}))} rules carry a resolvable authority")


def check_discovery(manifest: dict[str, Any], canonical: dict[str, dict[str, Path]]) -> None:
    """V7 — each artifact is where its tool looks, carrying what the tool reads.

    A surface in the manifest with no entry in DISCOVERY is reported, so a new
    tool cannot arrive with its discovery silently unverified; Devin is the one
    surface that is deliberately absent, and says so.
    """
    for surface in manifest["surfaces"]:
        if surface not in DISCOVERY and surface != "devin":
            fail("V7", f"{surface}: no discovery contract recorded — add what the tool reads to DISCOVERY")
    checked = 0
    for surface, kinds in DISCOVERY.items():
        if surface not in manifest["surfaces"]:
            continue
        for kind, (patterns, required) in kinds.items():
            # The surface's OWN layout must be a place its tool reads. Finding
            # the file is not enough: Cursor and Codex share `.agents/skills/`,
            # so a Codex layout pointed elsewhere still "found" Cursor's copy,
            # and would have gone blind the day Cursor's moved.
            published = manifest["surfaces"][surface]["layout"].get(kind)
            if published not in patterns:
                fail("V7", f"{surface}: publishes {kind} to {published}, which the tool does not read")
            for name in canonical.get(kind, {}):
                found = [REPO_ROOT / p.replace("{name}", name) for p in patterns]
                path = next((f for f in found if f.is_file()), None)
                if path is None:
                    fail("V7", f"{surface}: {kind}/{name} is not where the tool looks ({' or '.join(patterns)})")
                    continue
                checked += 1
                if not required:
                    continue
                fm = _front_matter(path.read_text(encoding="utf-8"))
                rel = path.relative_to(REPO_ROOT)
                if fm is None:
                    fail("V7", f"{rel} has no front-matter; the tool lists it by {', '.join(required)}")
                    continue
                for key in required:
                    if not fm.get(key):
                        fail("V7", f"{rel} front-matter is missing {key!r}")
                if "name" in required and fm.get("name") and fm["name"] != path.parent.name:
                    fail("V7", f"{rel} declares name {fm['name']!r}; the tool requires its folder name")
                if len(str(fm.get("description", ""))) > MAX_DESCRIPTION:
                    fail("V7", f"{rel} description exceeds {MAX_DESCRIPTION} characters")
    ok("V7", f"{checked} artifacts are where Claude Code, Cursor and Codex look for them")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--strict", action="store_true", help="treat warnings as failures")
    args = parser.parse_args()

    if not MANIFEST.is_file():
        sys.exit(f"missing manifest: {MANIFEST.relative_to(REPO_ROOT)}")
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    modes = manifest["modes"]
    canonical = collect_canonical(manifest)

    check_parity(manifest, canonical)
    check_skill_front_matter(canonical, modes)
    check_no_de_escalation(manifest, canonical, modes)
    check_mirror_fidelity(manifest, canonical)
    check_pointer_purity(manifest)
    check_rule_authority(canonical, manifest)
    check_discovery(manifest, canonical)

    for note in notes:
        print(f"  ok   {note}")
    for warning in warnings:
        print(f"  warn {warning}")

    if failures or (args.strict and warnings):
        print("\n[agentic] FAILED\n")
        for failure in failures:
            print(f"  FAIL {failure}")
        if args.strict:
            for warning in warnings:
                print(f"  FAIL (strict) {warning}")
        print(f"\n{len(failures) + (len(warnings) if args.strict else 0)} failure(s).")
        return 1

    print("\n[agentic] OK — surface is coherent across every tool")
    return 0


if __name__ == "__main__":
    sys.exit(main())
